customhost = "database-1.cxhvuo3rzi6k.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "leongkuanfei-employee"
customregion = "us-east-1"
